# Generated by Django 2.0.3 on 2019-02-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190219_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=16)),
                ('size', models.CharField(max_length=16)),
                ('toppingType', models.CharField(max_length=32)),
            ],
        ),
    ]
