# Generated by Django 2.0.3 on 2019-02-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('price', models.FloatField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
