# Generated by Django 2.0.3 on 2019-02-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_standard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Standard',
            new_name='Standard_pizza',
        ),
    ]
