# Generated by Django 2.0.3 on 2019-02-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_sub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subs',
        ),
    ]
