# Generated by Django 2.0.3 on 2019-02-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190225_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platter',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sicilian_pizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='standard_pizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
