# Generated by Django 2.0.3 on 2019-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190225_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='price_large',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='price_small',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='standard_pizza',
            name='price_large',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='standard_pizza',
            name='price_small',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
