# Generated by Django 2.0.3 on 2019-02-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20190225_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='price',
        ),
        migrations.AddField(
            model_name='sub',
            name='price_large',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='price_small',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
