# Generated by Django 2.0.3 on 2019-02-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20190225_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='price_large',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='price_small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
