# Generated by Django 2.0.3 on 2019-02-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20190225_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platter',
            name='price',
        ),
        migrations.AddField(
            model_name='platter',
            name='price_large',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='platter',
            name='price_small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
