# Generated by Django 2.0.3 on 2019-02-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_orders_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_tracking',
            name='order_numner',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders_tracking',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
