# Generated by Django 2.0.3 on 2019-02-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20190225_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(blank=True, null=True)),
                ('item', models.CharField(max_length=75)),
                ('toppings_extras', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='orders_tracking',
            old_name='order_numner',
            new_name='order_number',
        ),
    ]
