# Generated by Django 2.0.3 on 2019-02-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20190225_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='sicilian_pizza',
            name='full_description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard_pizza',
            name='full_description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
