# Generated by Django 2.0.3 on 2019-02-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20190226_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sicilian_pizza',
            old_name='full_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='standard_pizza',
            old_name='full_description',
            new_name='description',
        ),
    ]
